### ISSUE TITLE
How to access exports?

### ISSUE THREAD

**Issue by chasemccoy** [nhducit/gatsby-plugin-mdx#13]
I know that you can use the following syntax to export data from an `mdx` file:

```js
export const meta = {
  title: "Post Title"
}
```

But I am not sure how to access that data in Gatbsy in order to make use of it. Can I query for it in GraphQL? How can I pass the contents of my file to a component in order to render it?

In the example in the README, when the Gatsby node is created, the absolutely path is passed as the component, but I want to wrap my `mdx` component in a custom component in order to control how it is rendered. How would I do this?

**Comment by nhducit** [comment]
@chasemccoy I have no idea. TBH I don't have much experience with both gatsby and MDX

**Comment by slorber** [comment]
Hi

I've tried to make it work yesterday and couldn't figure it out.

The thing is, the Gatsby Remark plugin works in a very different way as it transform the markdown file to a HTML string, while MDX does transform your .mdx to a JSX component.

The thing is you should pass the JSX component path to Gatsby, but there's no way to tell Gatsby to extract the metadatas related to this component and inject them as context params. I tried to do this before calling createPage using mdx-js directly in node part, but ended up with a jsx component source as a string. 

Also didn't find any way to provide the "components" prop of MDX to customize the md style. Tried using Gatsby layout to provide the components prop but the `children()` is not the `MDXTag` component unfortunately. This could probably be solved if MDX did support providing these components with react context instead of prop, will open an issue for that.

**Comment by slorber** [comment]
Note I didn't find the NextJS example helpful, this is probably not only related to Gatsby integration: https://github.com/mdx-js/mdx/issues/152

**Comment by slorber** [comment]
I've done a VERY HACKY attempt to get exports on the node part:

```js
const getMDXExports = (mdxAbsolutePath) => {
  const jsAbsolutePath = mdxAbsolutePath + ".js";
  const jsDirname = path.dirname(jsAbsolutePath);
  if (!fs.existsSync(jsDirname)) {
    fs.mkdirSync(jsDirname);
  }

  const code = `
  import React from 'react'
  import { MDXTag } from '@mdx-js/tag'
  ${mdx.sync(fs.readFileSync(mdxAbsolutePath))}
  `;
  const codeTranspiled = babel.transform(code, {
    presets: ['es2015','react']
  }).code;

  fs.writeFileSync(jsAbsolutePath, codeTranspiled);
  const result = require(jsAbsolutePath);
  fs.unlinkSync(jsAbsolutePath);

  return result;
};
```

This almost work. The problem is that a .md file can import another .md file, so it fails miserably in such cases because node does not know how to require a md file.

This approach is not viable imho, we have to keep using the webpack loader if we and mdx transclusion to work fine.

In addition, even if I am able to get the tags on node part, I don't know how to inject these in the MDX page: layout does not receive page context and I don't know how to create a template for a mdx file.

IMHO Gatsby should allow us to write some kind of "componentWrapper"

**Comment by jennasalau** [comment]
I too am trying to wrap my markdown files in a template but it seems mdx will only work when passed directly into CreatePage. Is that correct?

**Comment by slorber** [comment]
@jennasalau @avigoldman has a working example here: https://github.com/gatsbyjs/gatsby/issues/312#issuecomment-398225446

**Comment by ChristopherBiscardi** [comment]
Since gatsby 2.0 is on the horizon, we're doing work to support it in https://github.com/ChristopherBiscardi/gatsby-mdx which has support for [mdx layouts](https://github.com/mdx-js/mdx#export-default), [default layouts](https://github.com/ChristopherBiscardi/gatsby-mdx#default-layouts) for different sources and [querying export values via GraphQL](https://github.com/ChristopherBiscardi/gatsby-mdx#graphql). I believe this satisfies all of the original requests in this thread so I would also encourage anyone looking for these features to upgrade to gatsby v2 and the gatsby-mdx plugin.

For example, in the original issue, the query to find the title field in the meta export is something like:

```graphql
query MDXQuery {
  allMdx {
    edges {
      node {
        exports {
          meta {
            title
          }
        }
      }
    }
  }
}
```

---

> Also didn't find any way to provide the "components" prop of MDX to customize the md style

You can use the [MDXProvider](https://github.com/ChristopherBiscardi/gatsby-mdx#using-design-system-components) component in a layout to do this.
